# Generated by Django 5.2.1 on 2026-06-11 18:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockercell',
            name='cell_type',
            field=models.CharField(choices=[('normal', '普通'), ('refrigerated', '冷藏')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='lockercell',
            name='max_temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='lockercell',
            name='min_temperature',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5),
        ),
    ]
